about
VovaRubakha/team-project pull request #21
Opened 2022-03-23 18:46 UTC by Mrichk0

це about

2022-03-23 21:25 UTC, VovaRubakha requested changes

2022-03-23 21:25 UTC, VovaRubakha commented on src/partials/about.html
> +<section class="about" id="How">
Change How to low-case (how)

2022-03-23 21:25 UTC, VovaRubakha commented on src/partials/about.html
> +      <div class="about__blok">
change "blok" to "block"

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +.about__blok {
change "blok" to "block"

2022-03-23 21:25 UTC, VovaRubakha commented on src/partials/about.html
> +        <button class="about__botton" type="button">
botton to button

2022-03-23 21:25 UTC, VovaRubakha commented on src/partials/about.html
> +            class="about__botton__icon"
botton to button

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +.about__botton {
botton to button

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +.about__botton__icon {
botton to button

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  background: #fff5f6;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  color: #ffa5ba;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  line-height: 21px;
21px change to 1.17

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +    line-height: 30px;
30px change to 1.15

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +    line-height: 34px;
34px change to 1.13

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  line-height: 39px;
39px change to 1.15

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  color: #d41443;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +    line-height: 55px;
51px change to 1.14

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +    line-height: 66px;
66px change to 1.14

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  color: #000000;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  color: #907e82;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  background: #ffffff;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  color: #d41443;
var

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +  &:hover {
add focus

2022-03-23 21:25 UTC, VovaRubakha commented on src/sass/layouts/_about.scss
> +    background-color: #ecebeb;
create and add var "--accent: #ecebeb;"

2022-03-24 10:56 UTC, Mrichk0 commented
@VovaRubakha done, comments addressed

2022-03-24 12:59 UTC, VovaRubakha approved these changes

2022-03-24 13:03 UTC, merged